
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 04 09:42:31 CEST 2012
//----------------------------------------------------

package it.m2j;

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Mon Jun 04 09:42:31 CEST 2012
  */
public class minic2jasminParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public minic2jasminParser() {super();}

  /** Constructor which sets the default scanner. */
  public minic2jasminParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\003\000\002\001\002\000\004\002\005\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\003\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$minic2jasminParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$minic2jasminParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$minic2jasminParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    
}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$minic2jasminParser$actions {


        

  private final minic2jasminParser parser;

  /** Constructor */
  CUP$minic2jasminParser$actions(minic2jasminParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$minic2jasminParser$do_action(
    int                        CUP$minic2jasminParser$act_num,
    java_cup.runtime.lr_parser CUP$minic2jasminParser$parser,
    java.util.Stack            CUP$minic2jasminParser$stack,
    int                        CUP$minic2jasminParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$minic2jasminParser$result;

      /* select the action based on the action number */
      switch (CUP$minic2jasminParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= prog 
            { 
              Object RESULT = null;
		 
              CUP$minic2jasminParser$result = new java_cup.runtime.Symbol(1/*prog*/, ((java_cup.runtime.Symbol)CUP$minic2jasminParser$stack.elementAt(CUP$minic2jasminParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$minic2jasminParser$stack.elementAt(CUP$minic2jasminParser$top-0)).right, RESULT);
            }
          return CUP$minic2jasminParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$minic2jasminParser$stack.elementAt(CUP$minic2jasminParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$minic2jasminParser$stack.elementAt(CUP$minic2jasminParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$minic2jasminParser$stack.elementAt(CUP$minic2jasminParser$top-1)).value;
		RESULT = start_val;
              CUP$minic2jasminParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$minic2jasminParser$stack.elementAt(CUP$minic2jasminParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$minic2jasminParser$stack.elementAt(CUP$minic2jasminParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$minic2jasminParser$parser.done_parsing();
          return CUP$minic2jasminParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

