
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 07 15:14:11 CEST 2012
//----------------------------------------------------

package it.m2j;

import java_cup.runtime.sym_interface;

/** CUP generated class containing symbol constants. */
public class minic2jasminSym implements sym_interface {
  /* terminals */
  public static final int OP_SIGN = 19;
  public static final int OP_GT = 24;
  public static final int DOUBLE = 38;
  public static final int TYPE_VOID = 5;
  public static final int OP_NOT = 28;
  public static final int SEMI = 30;
  public static final int OP_AND = 26;
  public static final int INT = 37;
  public static final int BRA_O = 31;
  public static final int OP_GET = 25;
  public static final int OP_DIV = 17;
  public static final int OP_DIFF = 15;
  public static final int BRA_C = 32;
  public static final int COMMA = 29;
  public static final int TYPE_INT = 3;
  public static final int EXTERN = 7;
  public static final int CONST_FLOAT = 42;
  public static final int ASSIGN = 11;
  public static final int IF = 8;
  public static final int ID = 39;
  public static final int OP_MOD = 18;
  public static final int OP_NEQ = 21;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int OP_LT = 22;
  public static final int BRA_CS = 34;
  public static final int OP_OR = 27;
  public static final int CONST_BOOL = 40;
  public static final int TYPE_FLOAT = 6;
  public static final int BRA_OS = 33;
  public static final int OP_TIME = 16;
  public static final int BRA_CG = 36;
  public static final int OP_LET = 23;
  public static final int ELSE = 9;
  public static final int TYPE_STRING = 4;
  public static final int BRA_OG = 35;
  public static final int WHILE = 10;
  public static final int CONST_STRING = 43;
  public static final int OP_EQ = 20;
  public static final int OP_PLUS = 14;
  public static final int TYPE_BOOL = 2;
  public static final int CONST_INT = 41;
public String[] TT;
	public minic2jasminSym(){
		TT = new String[44];
		TT[19]=new String("OP_SIGN");
		TT[24]=new String("OP_GT");
		TT[38]=new String("DOUBLE");
		TT[5]=new String("TYPE_VOID");
		TT[28]=new String("OP_NOT");
		TT[30]=new String("SEMI");
		TT[26]=new String("OP_AND");
		TT[37]=new String("INT");
		TT[31]=new String("BRA_O");
		TT[25]=new String("OP_GET");
		TT[17]=new String("OP_DIV");
		TT[15]=new String("OP_DIFF");
		TT[32]=new String("BRA_C");
		TT[29]=new String("COMMA");
		TT[3]=new String("TYPE_INT");
		TT[7]=new String("EXTERN");
		TT[42]=new String("CONST_FLOAT");
		TT[11]=new String("ASSIGN");
		TT[8]=new String("IF");
		TT[39]=new String("ID");
		TT[18]=new String("OP_MOD");
		TT[21]=new String("OP_NEQ");
		TT[0]=new String("EOF");
		TT[13]=new String("RETURN");
		TT[12]=new String("NEW");
		TT[1]=new String("error");
		TT[22]=new String("OP_LT");
		TT[34]=new String("BRA_CS");
		TT[27]=new String("OP_OR");
		TT[40]=new String("CONST_BOOL");
		TT[6]=new String("TYPE_FLOAT");
		TT[33]=new String("BRA_OS");
		TT[16]=new String("OP_TIME");
		TT[36]=new String("BRA_CG");
		TT[23]=new String("OP_LET");
		TT[9]=new String("ELSE");
		TT[4]=new String("TYPE_STRING");
		TT[35]=new String("BRA_OG");
		TT[10]=new String("WHILE");
		TT[43]=new String("CONST_STRING");
		TT[20]=new String("OP_EQ");
		TT[14]=new String("OP_PLUS");
		TT[2]=new String("TYPE_BOOL");
		TT[41]=new String("CONST_INT");
	}
public String getTT(int i){return TT[i];}
}
